import type { Metadata } from "next";
import "./globals.css";
import TranslationsProvider from "../i18n/TranslationProvider";
import initTranslations from "../i18n/i18n";
import { AboutLayoutProps } from "./about/layout";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const i18nNamespaces = ["home", "common"];

export default async function RootLayout({
  children,
  params: { locale },
}: AboutLayoutProps) {
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale}>
      <TranslationsProvider
        locale={locale}
        namespaces={i18nNamespaces}
        resources={resources}
      >
        <body>
          <Footer />
          {children}
        </body>
      </TranslationsProvider>
    </html>
  );
}
